### ISSUE TITLE
Compatibility with Internet Explorer

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#350]
Contao 4.x.x now supports IE9 and higher. Is this correct? Or 10?

Ref.: https://github.com/contao/docs/blob/4.0/manual/en/01-installation/configuring-the-live-server.md#contao-system-requirements

**Comment by aschempp** [comment]
@leofeyer ?

**Comment by leofeyer** [comment]
There is no official statement yet. We have dropped support for IE8 but we have not discussed whether we want to support IE9+ or IE10+.

I'd vote for IE10+.

**Comment by lionel-m** [comment]
I am also for IE10+.

**Comment by aschempp** [comment]
I am a friend of progressive enhancements. Things should work but they don't need to be fancy in older browsers. No idea what that would mean ^^

**Comment by leofeyer** [comment]
:LOL:

**Comment by no-one** [comment]
Keep in mind, that MS will drop support for older versions of IE soon: https://support.microsoft.com/en-us/lifecycle#gp/Microsoft-Internet-Explorer

**Comment by aschempp** [comment]
Just because they are not supported does not mean they are not in use ;-)

Personally I don't see a reason to drop any support. If something does not work, then we just need to check wether it's necessary or just a gimmick in all browsers. I don't care if the rows are colored on hover in IE9, but the buttons should work (as a general example)…

**Comment by lionel-m** [comment]
Resolved in #440
